version: '3.4'

services:
  trimania:
    image: ${DOCKER_REGISTRY-}trimania
    build:
      context: .
      dockerfile: Trimania/Dockerfile
  mysql:
     image: "mysql"
     container_name: "mysql"
     ports:
         - "3306:3306"
     environment:
         MYSQL_ROOT_PASSWORD: "tr1man1a"
         MYSQL_USER: "trimania"
         MYSQL_PASSWORD: "tr1man1a"
         MYSQL_DATABASE: "trimania"